// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(PackageDbContext))]
    [Migration("20221022083651_AddedDataCanteenTest")]
    partial class AddedDataCanteenTest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Core.Domain.Canteen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("City")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OfferHotMeals")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Canteens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = 3,
                            Name = "LA",
                            OfferHotMeals = true
                        },
                        new
                        {
                            Id = 2,
                            City = 1,
                            Name = "LD 2",
                            OfferHotMeals = false
                        });
                });

            modelBuilder.Entity("Core.Domain.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CanteenId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Core.Domain.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AvailableUntil")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CanteenId")
                        .HasColumnType("int");

                    b.Property<int>("City")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Meal")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PickUp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CanteenId");

                    b.HasIndex("StudentId");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableUntil = new DateTime(2022, 10, 25, 10, 36, 51, 312, DateTimeKind.Local).AddTicks(640),
                            City = 1,
                            Description = "This is a package",
                            Meal = 1,
                            Name = "Package 1",
                            PickUp = new DateTime(2022, 10, 22, 10, 36, 51, 312, DateTimeKind.Local).AddTicks(605),
                            Price = 10m,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            AvailableUntil = new DateTime(2022, 10, 25, 10, 36, 51, 312, DateTimeKind.Local).AddTicks(647),
                            City = 1,
                            Description = "This is a package",
                            Meal = 1,
                            Name = "Package 2",
                            PickUp = new DateTime(2022, 10, 22, 10, 36, 51, 312, DateTimeKind.Local).AddTicks(644),
                            Price = 10m,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 3,
                            AvailableUntil = new DateTime(2022, 10, 25, 10, 36, 51, 312, DateTimeKind.Local).AddTicks(651),
                            City = 3,
                            Description = "This is a package",
                            Meal = 1,
                            Name = "Package 3",
                            PickUp = new DateTime(2022, 10, 22, 10, 36, 51, 312, DateTimeKind.Local).AddTicks(649),
                            Price = 10m
                        },
                        new
                        {
                            Id = 4,
                            AvailableUntil = new DateTime(2022, 10, 25, 10, 36, 51, 312, DateTimeKind.Local).AddTicks(655),
                            City = 3,
                            Description = "This is a package",
                            Meal = 1,
                            Name = "Package 4",
                            PickUp = new DateTime(2022, 10, 22, 10, 36, 51, 312, DateTimeKind.Local).AddTicks(653),
                            Price = 10m
                        });
                });

            modelBuilder.Entity("Core.Domain.PackageProducts", b =>
                {
                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("PackageId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("PackageProducts");

                    b.HasData(
                        new
                        {
                            PackageId = 1,
                            ProductId = 1,
                            Id = 0
                        },
                        new
                        {
                            PackageId = 1,
                            ProductId = 2,
                            Id = 0
                        },
                        new
                        {
                            PackageId = 1,
                            ProductId = 3,
                            Id = 0
                        },
                        new
                        {
                            PackageId = 1,
                            ProductId = 4,
                            Id = 0
                        },
                        new
                        {
                            PackageId = 2,
                            ProductId = 1,
                            Id = 0
                        },
                        new
                        {
                            PackageId = 2,
                            ProductId = 2,
                            Id = 0
                        },
                        new
                        {
                            PackageId = 2,
                            ProductId = 3,
                            Id = 0
                        });
                });

            modelBuilder.Entity("Core.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("ContainsAlcohol")
                        .HasColumnType("bit");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContainsAlcohol = false,
                            Image = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.ah.nl%2Fproducten%2Fproduct%2Fwi",
                            Name = "Product 1"
                        },
                        new
                        {
                            Id = 2,
                            ContainsAlcohol = false,
                            Image = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.ah.nl%2Fproducten%2Fproduct%2Fwi",
                            Name = "Product 2"
                        },
                        new
                        {
                            Id = 3,
                            ContainsAlcohol = false,
                            Image = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.ah.nl%2Fproducten%2Fproduct%2Fwi",
                            Name = "Product 3"
                        },
                        new
                        {
                            Id = 4,
                            ContainsAlcohol = false,
                            Image = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.ah.nl%2Fproducten%2Fproduct%2Fwi",
                            Name = "Product 4"
                        },
                        new
                        {
                            Id = 5,
                            ContainsAlcohol = false,
                            Image = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.ah.nl%2Fproducten%2Fproduct%2Fwi",
                            Name = "Product 5"
                        },
                        new
                        {
                            Id = 6,
                            ContainsAlcohol = false,
                            Image = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.ah.nl%2Fproducten%2Fproduct%2Fwi",
                            Name = "Product 6"
                        });
                });

            modelBuilder.Entity("Core.Domain.ReservedPackage", b =>
                {
                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("PackageId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("ReservedPackage");

                    b.HasData(
                        new
                        {
                            PackageId = 1,
                            StudentId = 1,
                            Id = 0
                        },
                        new
                        {
                            PackageId = 2,
                            StudentId = 1,
                            Id = 0
                        });
                });

            modelBuilder.Entity("Core.Domain.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("City")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = 3,
                            Name = "Student 1",
                            PhoneNumber = "0612345678"
                        },
                        new
                        {
                            Id = 2,
                            City = 1,
                            Name = "Student 2",
                            PhoneNumber = "0612345678"
                        });
                });

            modelBuilder.Entity("PackageProduct", b =>
                {
                    b.Property<int>("PackagesId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("PackagesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("PackageProduct");
                });

            modelBuilder.Entity("Core.Domain.Package", b =>
                {
                    b.HasOne("Core.Domain.Canteen", "Canteen")
                        .WithMany("Packages")
                        .HasForeignKey("CanteenId");

                    b.HasOne("Core.Domain.Student", "Student")
                        .WithMany("Packages")
                        .HasForeignKey("StudentId");

                    b.Navigation("Canteen");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Core.Domain.PackageProducts", b =>
                {
                    b.HasOne("Core.Domain.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Core.Domain.ReservedPackage", b =>
                {
                    b.HasOne("Core.Domain.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PackageProduct", b =>
                {
                    b.HasOne("Core.Domain.Package", null)
                        .WithMany()
                        .HasForeignKey("PackagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Canteen", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("Core.Domain.Student", b =>
                {
                    b.Navigation("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
